var annotated_dup =
[
    [ "calpha", null, [
      [ "lsp", null, [
        [ "Diagnostic", "de/da2/structcalpha_1_1lsp_1_1Diagnostic.html", null ],
        [ "DocumentState", "d2/dc4/structcalpha_1_1lsp_1_1DocumentState.html", null ],
        [ "JSONRPCHandler", "db/db1/classcalpha_1_1lsp_1_1JSONRPCHandler.html", null ],
        [ "Location", "de/df6/structcalpha_1_1lsp_1_1Location.html", null ],
        [ "LSPServer", "da/d48/classcalpha_1_1lsp_1_1LSPServer.html", null ],
        [ "NotificationHandler", "d6/d7a/classcalpha_1_1lsp_1_1NotificationHandler.html", null ],
        [ "Position", "d3/d42/structcalpha_1_1lsp_1_1Position.html", null ],
        [ "Range", "d2/de9/structcalpha_1_1lsp_1_1Range.html", null ]
      ] ],
      [ "ArrayAccess", "d8/d3a/classcalpha_1_1ArrayAccess.html", null ],
      [ "ArrayAllocation", "df/d7b/classcalpha_1_1ArrayAllocation.html", null ],
      [ "ArraySemanticType", "d7/d1e/classcalpha_1_1ArraySemanticType.html", null ],
      [ "Assignment", "d2/d24/classcalpha_1_1Assignment.html", null ],
      [ "ASTNode", "d8/d03/classcalpha_1_1ASTNode.html", null ],
      [ "BasicSemanticType", "dd/d28/classcalpha_1_1BasicSemanticType.html", null ],
      [ "BasicType", "de/d8f/classcalpha_1_1BasicType.html", null ],
      [ "BinaryExpression", "d9/d4a/classcalpha_1_1BinaryExpression.html", null ],
      [ "BlockStatement", "dc/df9/classcalpha_1_1BlockStatement.html", null ],
      [ "CodeGenerator", "df/d8b/classcalpha_1_1CodeGenerator.html", null ],
      [ "CodeGeneratorError", "da/d09/classcalpha_1_1CodeGeneratorError.html", null ],
      [ "Expression", "d7/db9/classcalpha_1_1Expression.html", null ],
      [ "ExpressionStatement", "d4/de6/classcalpha_1_1ExpressionStatement.html", null ],
      [ "FunctionCall", "d4/dec/classcalpha_1_1FunctionCall.html", null ],
      [ "FunctionDeclaration", "d5/d3f/classcalpha_1_1FunctionDeclaration.html", null ],
      [ "FunctionSemanticType", "d3/d41/classcalpha_1_1FunctionSemanticType.html", null ],
      [ "Identifier", "df/d04/classcalpha_1_1Identifier.html", null ],
      [ "IfStatement", "dc/d96/classcalpha_1_1IfStatement.html", null ],
      [ "ImportStatement", "d7/d48/classcalpha_1_1ImportStatement.html", null ],
      [ "LabelGenerator", "d7/d85/classcalpha_1_1LabelGenerator.html", null ],
      [ "LayoutDeclaration", "d6/dbc/classcalpha_1_1LayoutDeclaration.html", null ],
      [ "LayoutInitialization", "d3/d93/classcalpha_1_1LayoutInitialization.html", null ],
      [ "LayoutMember", "d5/d96/classcalpha_1_1LayoutMember.html", null ],
      [ "LayoutSemanticType", "d5/d97/classcalpha_1_1LayoutSemanticType.html", "d5/d97/classcalpha_1_1LayoutSemanticType" ],
      [ "LayoutType", "d8/d6b/classcalpha_1_1LayoutType.html", null ],
      [ "Lexer", "d7/dd9/classcalpha_1_1Lexer.html", null ],
      [ "Literal", "dc/d39/classcalpha_1_1Literal.html", null ],
      [ "MemberAccess", "df/d3f/classcalpha_1_1MemberAccess.html", null ],
      [ "MemoryManager", "d0/df0/classcalpha_1_1MemoryManager.html", null ],
      [ "NamespaceAccess", "dd/dfc/classcalpha_1_1NamespaceAccess.html", null ],
      [ "NamespaceDeclaration", "da/d64/classcalpha_1_1NamespaceDeclaration.html", null ],
      [ "Parameter", "d0/db6/classcalpha_1_1Parameter.html", null ],
      [ "Parser", "d0/d37/classcalpha_1_1Parser.html", "d0/d37/classcalpha_1_1Parser" ],
      [ "PointerSemanticType", "df/ded/classcalpha_1_1PointerSemanticType.html", null ],
      [ "PointerType", "de/dfd/classcalpha_1_1PointerType.html", null ],
      [ "Preprocessor", "db/d0a/classcalpha_1_1Preprocessor.html", null ],
      [ "Program", "db/d59/classcalpha_1_1Program.html", null ],
      [ "RegisterAllocator", "d5/d94/classcalpha_1_1RegisterAllocator.html", null ],
      [ "ReturnStatement", "d8/d69/classcalpha_1_1ReturnStatement.html", null ],
      [ "Scope", "d3/d30/classcalpha_1_1Scope.html", null ],
      [ "SemanticAnalyzer", "de/d88/classcalpha_1_1SemanticAnalyzer.html", null ],
      [ "SemanticError", "dc/d40/classcalpha_1_1SemanticError.html", null ],
      [ "SemanticType", "d5/d9e/classcalpha_1_1SemanticType.html", null ],
      [ "Statement", "da/d15/classcalpha_1_1Statement.html", null ],
      [ "StringLiteral", "d0/ddc/classcalpha_1_1StringLiteral.html", null ],
      [ "Symbol", "d7/d0f/classcalpha_1_1Symbol.html", null ],
      [ "SymbolTable", "df/d74/classcalpha_1_1SymbolTable.html", null ],
      [ "SyscallExpression", "de/dec/classcalpha_1_1SyscallExpression.html", null ],
      [ "Token", "d1/d04/structcalpha_1_1Token.html", null ],
      [ "Type", "d0/d84/classcalpha_1_1Type.html", null ],
      [ "TypeCast", "dd/db6/classcalpha_1_1TypeCast.html", null ],
      [ "UnaryExpression", "df/d6e/classcalpha_1_1UnaryExpression.html", null ],
      [ "VariableDeclaration", "d7/d9a/classcalpha_1_1VariableDeclaration.html", null ],
      [ "WhileStatement", "d3/de5/classcalpha_1_1WhileStatement.html", null ]
    ] ]
];